### ISSUE TITLE
Crash when seed node DNS name cannot be found

### ISSUE THREAD

**Issue by metalicjames** [Gehhilfe/vtc-scanner#2]
The scanner crashes if the domain name of a node cannot be found.

Log output:

```
webapp_1  | 
webapp_1  | > vtc-scanner@0.0.1 start /usr/src/app
webapp_1  | > node server.js
webapp_1  | 
webapp_1  | info: Seed notes added
webapp_1  | info: Bootstrapping pool search with seeds
webapp_1  | debug:  Error: queryA ENOTFOUND pool.boxienet.net
webapp_1  |     at errnoException (dns.js:50:10)
webapp_1  |     at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
```

**Comment by gehhilfe** [comment]
Hi James,
will fix it today.
